metadata:
  name: ssms-api

build:
  artifacts:
    - image: 0xdvc/ssms-api
      context: ../../
      jib: {}

deploy:
  kubectl:
    manifests:
      - kubernetes/deployment.yaml
      - kubernetes/service.yaml